apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "webhook.fullname" . }}-role
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "webhook.fullname" . }}-role-binding
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "webhook.serviceAccountName" . }}
    namespace: {{ include "webhook.fullname" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "webhook.fullname" . }}-role
  apiGroup: rbac.authorization.k8s.io
---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "webhook.serviceAccountName" . }}
  namespace: {{ include "webhook.fullname" . }}
  labels:
    {{- include "webhook.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}