name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    # Step 3: Build the Docker image
    - name: Build Docker image
      run: docker build -t ghcr.io/devops-yug/workload-label-mutating-webhook/webhook:0.1.1 .

    # Step 4: Tag and push Docker image
    - name: Push Docker image
      run: |
        docker push ghcr.io/devops-yug/workload-label-mutating-webhook/webhook:0.1.1